name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs  # Install MkDocs
        pip install mkdocs-material  # If you're using the Material theme, or your specific theme
    
    - name: Build the MkDocs site
      run: mkdocs build  # This will generate the static site in the 'site/' folder by default
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        publish_dir: ./site  # Directory where MkDocs generates the static files

